# Generated by Django 5.2.4 on 2025-10-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='cep',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='lead',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
