# Generated by Django 5.2.4 on 2025-10-31 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lead_cep_lead_telefone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-criado_em']},
        ),
    ]
