# Generated by Django 5.2.4 on 2025-10-31 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lead_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
