# Generated by Django 5.2.4 on 2025-10-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('primeiro_paragrafo', models.TextField()),
                ('primeira_imagem', models.ImageField(blank=True, null=True, upload_to='artigos/')),
                ('segundo_paragrafo', models.TextField(blank=True, null=True)),
                ('segunda_imagem', models.ImageField(blank=True, null=True, upload_to='artigos/')),
                ('terceiro_paragrafo', models.TextField(blank=True, null=True)),
                ('terceira_imagem', models.ImageField(blank=True, null=True, upload_to='artigos/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
