# Generated by Django 5.2.4 on 2025-10-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigo',
            old_name='primeiro_paragrafo',
            new_name='resumo',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='primeira_imagem',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='segunda_imagem',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='segundo_paragrafo',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='terceira_imagem',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='terceiro_paragrafo',
        ),
        migrations.AddField(
            model_name='artigo',
            name='conteudo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
    ]
