# Generated by Django 5.2.4 on 2025-10-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_primeiro_paragrafo_artigo_resumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='resumo',
            field=models.TextField(default=''),
        ),
    ]
