# Generated by Django 5.2.4 on 2025-10-29 23:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_artigo_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='data_publicacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
